// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqDYtaaeB7pBtiR2KRDekF9qjsWjycnYo',
    appId: '1:956613694779:android:01b49a99b3d0f8cd6a931e',
    messagingSenderId: '956613694779',
    projectId: 'yala-chat-80ab6',
    storageBucket: 'yala-chat-80ab6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpWcGThO1S6vxBDks299UXD7Uc1Xlu6jQ',
    appId: '1:956613694779:ios:8001bc66e7533b196a931e',
    messagingSenderId: '956613694779',
    projectId: 'yala-chat-80ab6',
    storageBucket: 'yala-chat-80ab6.appspot.com',
    iosClientId: '956613694779-ar8saftuqdg4j0ravr6fka6q97bcdtqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
